{% set name = "distro" %}
{% set version = "1.8.0" %}
{% set sha256 = "02e111d1dc6a50abb8eed6bf31c3e48ed8b0830d1ea2a1b78c61765c2513fdd8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  entry_points:
    - distro = distro.distro:main
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6

test:
  source_files:
    - tests
  commands:
    - pip check
    - distro --help
    - pytest -vvv --capture=tee-sys tests
  imports:
    - distro
  requires:
    - pip
    - pytest

about:
  home: https://github.com/nir0s/distro
  license: Apache-2.0
  license_file: LICENSE
  summary: Provides information about the OS distribution it runs on, such as a reliable machine-readable ID, or version information.
  doc_url: http://distro.readthedocs.io/en/latest/
  dev_url: https://github.com/nir0s/distro

extra:
  recipe-maintainers:
    - abloemert
    - thewchan
