{% set name = "distro" %}
{% set version = "1.7.0" %}
{% set sha256 = "151aeccf60c216402932b52e40ee477a939f8d58898927378a02abbe852c1c39" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  entry_points:
    - distro = distro:main
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6

test:
  commands:
    - distro --help
  imports:
    - distro

about:
  home: https://github.com/nir0s/distro
  license: Apache-2.0
  license_file: LICENSE
  summary: Linux Distribution - a Linux OS platform information API
  doc_url: http://distro.readthedocs.io/en/latest/
  dev_url: https://github.com/nir0s/distro

extra:
  recipe-maintainers:
    - abloemert
